export const ERROR_CODES = [
  'VALIDATION_ERROR',
  'UNAUTHENTICATED',
  'TOKEN_EXPIRED',
  'INVALID_CREDENTIALS',
  'EMAIL_NOT_VERIFIED',
  'ACCOUNT_DISABLED',
  'FORBIDDEN',
  'PERMISSION_DENIED',
  'NOT_FOUND',
  'CONFLICT',
  'EMAIL_ALREADY_EXISTS',
  'RATE_LIMITED',
  'FILE_TOO_LARGE',
  'UNSUPPORTED_MEDIA_TYPE',
  'INTERNAL_ERROR',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number] | `${string}_NOT_FOUND`;
