'use client';

import Link from 'next/link';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BookOpen, Check, RefreshCw, Sparkles, Wand2 } from 'lucide-react';
import { toast } from 'sonner';
import { PERMISSIONS } from '@digisoft/shared';
import { ApiError } from '@/lib/api-client';
import { aiService } from '@/services/ai.service';
import { ticketsService } from '@/services/tickets.service';
import { useAuthStore } from '@/stores/auth.store';
import { useComposerStore } from '@/stores/composer.store';
import { formatDateTime } from '@/lib/utils';
import type { AiInsightDto, TicketDetail } from '@/types/api';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { EmptyState, LoadingState } from '@/components/ui/states';

const SENTIMENT_VARIANT: Record<string, 'success' | 'warning' | 'danger' | 'default'> = {
  POSITIVE: 'success',
  NEUTRAL: 'default',
  NEGATIVE: 'warning',
  FRUSTRATED: 'danger',
};

function byType(insights: AiInsightDto[] | undefined, type: AiInsightDto['type']) {
  return insights?.find((insight) => insight.type === type);
}

/**
 * The assistant, beside the ticket it is talking about. Nothing here acts on its own:
 * a suggestion becomes a change only when an agent presses the button, and a draft
 * reply lands in the composer for them to edit and send.
 */
export function TicketAiPanel({ ticket }: { ticket: TicketDetail }) {
  const queryClient = useQueryClient();
  const can = useAuthStore((state) => state.can);
  const setDraft = useComposerStore((state) => state.setDraft);

  const settings = useQuery({ queryKey: ['ai-settings'], queryFn: aiService.settings });
  const insights = useQuery({
    queryKey: ['ai-insights', ticket.id],
    queryFn: () => aiService.forTicket(ticket.id),
  });
  const articles = useQuery({
    queryKey: ['ai-articles', ticket.id],
    queryFn: () => aiService.articles(ticket.id),
  });

  const generate = useMutation({
    mutationFn: (type: 'SUMMARY' | 'SENTIMENT' | 'INTENT' | 'SUGGESTED_REPLY') =>
      aiService.generate(ticket.id, { type, refresh: true }),
    onSuccess: async (insight) => {
      await queryClient.invalidateQueries({ queryKey: ['ai-insights', ticket.id] });
      if (insight.status === 'FAILED') {
        toast.error(insight.error ?? 'The assistant could not answer.');
      }
    },
    onError: (error) => toast.error(error instanceof ApiError ? error.message : 'The assistant failed.'),
  });

  const applyIntent = useMutation({
    mutationFn: (input: { categoryId?: string; priorityId?: string }) =>
      input.priorityId
        ? ticketsService.changePriority(ticket.id, { priorityId: input.priorityId })
        : ticketsService.update(ticket.id, { categoryId: input.categoryId ?? null }),
    onSuccess: async () => {
      await queryClient.invalidateQueries({ queryKey: ['ticket', ticket.id] });
      toast.success('Ticket updated');
    },
    onError: (error) => toast.error(error instanceof ApiError ? error.message : 'Unable to apply.'),
  });

  if (!can(PERMISSIONS.AI_USE)) {
    return <EmptyState title="Not available" description="Your role does not include the assistant." />;
  }
  if (settings.isPending) {
    return <LoadingState />;
  }
  if (!settings.data?.isEnabled) {
    return (
      <div className="p-4">
        <EmptyState
          title="The assistant is switched off"
          description="An administrator can turn it on in Settings → Assistant, with or without a provider key."
          action={
            can(PERMISSIONS.AI_MANAGE) ? (
              <Button asChild variant="outline">
                <Link href="/settings/ai">Open settings</Link>
              </Button>
            ) : null
          }
        />
      </div>
    );
  }

  const summary = byType(insights.data, 'SUMMARY');
  const sentiment = byType(insights.data, 'SENTIMENT');
  const intent = byType(insights.data, 'INTENT');
  const reply = byType(insights.data, 'SUGGESTED_REPLY');
  const providerLabel =
    settings.data.provider === 'HEURISTIC'
      ? 'rule-based analysis (no provider configured)'
      : `${settings.data.model}`;

  return (
    <div className="space-y-4 p-4">
      <p className="text-xs text-muted-foreground">
        <Sparkles className="mr-1 inline h-3 w-3" aria-hidden />
        Generated by {providerLabel}. Check anything before you send it.
      </p>

      <Card>
        <CardHeader className="flex-row items-center justify-between space-y-0 pb-2">
          <CardTitle className="text-base">Summary</CardTitle>
          <Button
            variant="ghost"
            size="sm"
            loading={generate.isPending && generate.variables === 'SUMMARY'}
            onClick={() => generate.mutate('SUMMARY')}
          >
            <RefreshCw className="h-3.5 w-3.5" aria-hidden />
            {summary ? 'Refresh' : 'Generate'}
          </Button>
        </CardHeader>
        <CardContent className="space-y-2">
          {summary?.status === 'READY' ? (
            <>
              <p className="text-sm">{summary.content.text}</p>
              <ul className="space-y-1 text-xs text-muted-foreground">
                {(summary.content.highlights ?? []).map((line) => (
                  <li key={line}>• {line}</li>
                ))}
              </ul>
              <p className="text-[11px] text-muted-foreground">
                {formatDateTime(summary.createdAt)} · {summary.model}
              </p>
            </>
          ) : summary?.status === 'FAILED' ? (
            <p className="text-sm text-destructive">{summary.error}</p>
          ) : (
            <p className="text-sm text-muted-foreground">Nothing generated yet.</p>
          )}
        </CardContent>
      </Card>

      <div className="grid gap-4 sm:grid-cols-2">
        <Card>
          <CardHeader className="flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-base">Sentiment</CardTitle>
            <Button
              variant="ghost"
              size="sm"
              loading={generate.isPending && generate.variables === 'SENTIMENT'}
              onClick={() => generate.mutate('SENTIMENT')}
            >
              <RefreshCw className="h-3.5 w-3.5" aria-hidden />
            </Button>
          </CardHeader>
          <CardContent className="space-y-2">
            {sentiment?.status === 'READY' && sentiment.content.sentiment ? (
              <>
                <Badge variant={SENTIMENT_VARIANT[sentiment.content.sentiment] ?? 'default'}>
                  {sentiment.content.sentiment.toLowerCase()}
                </Badge>
                <p className="text-xs text-muted-foreground">{sentiment.content.rationale}</p>
              </>
            ) : sentiment?.status === 'FAILED' ? (
              <p className="text-sm text-destructive">{sentiment.error}</p>
            ) : (
              <p className="text-sm text-muted-foreground">Not analysed yet.</p>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-base">Intent</CardTitle>
            <Button
              variant="ghost"
              size="sm"
              loading={generate.isPending && generate.variables === 'INTENT'}
              onClick={() => generate.mutate('INTENT')}
            >
              <RefreshCw className="h-3.5 w-3.5" aria-hidden />
            </Button>
          </CardHeader>
          <CardContent className="space-y-2">
            {intent?.status === 'READY' ? (
              <>
                <p className="text-sm font-medium">{intent.content.intent}</p>
                <p className="text-xs text-muted-foreground">
                  Urgency {intent.content.urgency?.toLowerCase()} · confidence{' '}
                  {Math.round((intent.content.confidence ?? 0) * 100)}%
                </p>
                <div className="flex flex-wrap gap-2 pt-1">
                  {intent.content.categoryId && intent.content.categoryId !== ticket.category?.id ? (
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => applyIntent.mutate({ categoryId: intent.content.categoryId! })}
                    >
                      <Check className="h-3.5 w-3.5" aria-hidden />
                      Set {intent.content.categoryName}
                    </Button>
                  ) : null}
                  {intent.content.priorityId && intent.content.priorityId !== ticket.priority.id ? (
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => applyIntent.mutate({ priorityId: intent.content.priorityId! })}
                    >
                      <Check className="h-3.5 w-3.5" aria-hidden />
                      Set {intent.content.priorityName} priority
                    </Button>
                  ) : null}
                </div>
              </>
            ) : intent?.status === 'FAILED' ? (
              <p className="text-sm text-destructive">{intent.error}</p>
            ) : (
              <p className="text-sm text-muted-foreground">Not classified yet.</p>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="flex-row items-center justify-between space-y-0 pb-2">
          <div>
            <CardTitle className="text-base">Suggested reply</CardTitle>
            <CardDescription>
              A draft for you to edit. Nothing is sent until you send it.
            </CardDescription>
          </div>
          <Button
            variant="ghost"
            size="sm"
            loading={generate.isPending && generate.variables === 'SUGGESTED_REPLY'}
            onClick={() => generate.mutate('SUGGESTED_REPLY')}
          >
            <Wand2 className="h-3.5 w-3.5" aria-hidden />
            {reply ? 'Redraft' : 'Draft a reply'}
          </Button>
        </CardHeader>
        <CardContent className="space-y-3">
          {reply?.status === 'READY' && reply.content.text ? (
            <>
              {!reply.content.grounded ? (
                <p className="rounded-md bg-amber-100 px-3 py-2 text-xs text-amber-900 dark:bg-amber-950 dark:text-amber-200">
                  No knowledge base article matched this ticket, so the draft asks for detail
                  rather than answering.
                </p>
              ) : null}
              <p className="whitespace-pre-wrap rounded-md border border-border p-3 text-sm">
                {reply.content.text}
              </p>
              <Button size="sm" onClick={() => setDraft(ticket.id, reply.content.text ?? '')}>
                Use this draft
              </Button>
            </>
          ) : reply?.status === 'FAILED' ? (
            <p className="text-sm text-destructive">{reply.error}</p>
          ) : (
            <p className="text-sm text-muted-foreground">No draft yet.</p>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="flex items-center gap-2 text-base">
            <BookOpen className="h-4 w-4" aria-hidden />
            Knowledge base matches
          </CardTitle>
        </CardHeader>
        <CardContent>
          {articles.data && articles.data.length > 0 ? (
            <ul className="space-y-2">
              {articles.data.map((article) => (
                <li key={article.id}>
                  <Link className="text-sm hover:underline" href={`/knowledge-base/${article.id}`}>
                    {article.title}
                  </Link>
                  {article.summary ? (
                    <p className="text-xs text-muted-foreground">{article.summary}</p>
                  ) : null}
                </li>
              ))}
            </ul>
          ) : (
            <p className="text-sm text-muted-foreground">
              Nothing in the knowledge base matches this ticket yet.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
